name: zod
description: A starting point for Dart libraries or applications.
version: 1.2.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  fpdart: ^1.1.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
